"""add post thumbnail_url

Revision ID: fe2b02b2eb37
Revises: c92724d4cd21
Create Date: 2026-08-17 18:20:08.419220

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fe2b02b2eb37'
down_revision: str | Sequence[str] | None = 'c92724d4cd21'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'thumbnail_url')
    # ### end Alembic commands ###
